apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 10Gi
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /pv-share
    server: 10.240.0.170
  persistentVolumeReclaimPolicy: Retain